### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by agdturner**
Remove this for the clean theme as it should be added automatically.

### CODE REVIEW

**Comment by agdturner** [comment]
Sorry, this is not needed. It only got added to my branch as I tried to figure out how to add the clean theme which got added into the quarto build process.

**Comment by patricia-ternes** [comment]
Hi Andy,

I think that now we are using the `clean-revealjs` theme, this is a good change.
This theme demands an extension, so to build locally we need to create this additional folder.

We can just remove the folder from the push, but I will 100% forget to do.

**Review by patricia-ternes — COMMENTED** [review]
I think you should approve this PR

**Review by patricia-ternes — APPROVED** [review]
You can merge this PR!

**Pull request merged**
